<?php defined('BASEPATH') OR exit('No direct script access allowed');
?><!DOCTYPE html>
<html lang="en">
<head>
    <?php $this->load->view('_snippets/head_resources'); ?>
</head>
<body>
<?php $this->load->view('_snippets/header'); ?>

<!-- .container start -->
<div class="container">
    <h1 class="display-4 mb-3">Generate <span class="text-info">Node JS</span> Migration Script</h1>

    <!-- #card-form start -->
    <div id="card-form" class="card border-info mb-3">
        <h5 class="card-header bg-info text-white"><i class="fas fa-bolt fa-fw"></i> Generate Script Form</h5>
        <div class="card-body">
            <p>This template generates a skeleton migration script with some instructions on how to create and drop tables.</p>
            <form method="post" data-parsley-validate>
                <div class="form-group">
                    <label class="control-label">Script Name <span class="text-danger">*</span></label>
                    <input class="form-control" type="text" id="script_name" name="script_name"
                        placeholder="create-sample-table" value="<?=set_value('script_name');?>"
                        pattern="<?=REGEX_PARSLEY_FILENAME_JS;?>" required/>
                </div>
                <p class="help-block">Script name criteria:</p>
                <ul class="help-block">
                    <li>Must be in <span class="font-monospace text-pink">kebab-case</span>.</li>
                    <li>Cannot begin with numbers.</li>
                </ul>
                <p class="help-block">Note: Do not include the version number; it will be generated by system.</p>

                <div class="form-group">
                    <label class="control-label">Table Name <span class="text-danger">*</span></label>
                    <input class="form-control" type="text" id="table_name" name="table_name"
                        placeholder="SampleTable" value="<?=set_value('table_name');?>"
                        pattern="<?=REGEX_PARSLEY_TABLENAME_JS;?>" required/>
                </div>
                <p class="help-block">Table name criteria:</p>
                <ul class="help-block">
                    <li>Must be in <span class="font-monospace text-pink">PascalCase</span>.</li>
                    <li>Cannot begin with numbers.</li>
                </ul>

                <div class="form-group">
                    <label class="control-label">Schema Name <span class="text-danger">*</span></label>
                    <input class="form-control" type="text" id="schema_name" name="schema_name"
                        placeholder="sampleTable" value="<?=set_value('schema_name');?>"
                        pattern="<?=REGEX_PARSLEY_SCHEMANAME_JS;?>" required/>
                </div>
                <p class="help-block">Schema name criteria:</p>
                <ul class="help-block">
                    <li>Must be in <span class="font-monospace text-pink">camelCase</span>.</li>
                    <li>Cannot begin with numbers.</li>
                </ul>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        Generate Script <i class="fas fa-check fa-fw"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <!-- #card-form end -->

    <!-- #card-script start -->
    <div id="card-script" class="card border-secondary mb-3">
        <h5 class="card-header bg-secondary text-white"><i class="fas fa-code fa-fw"></i> Script Preview</h5>
        <div class="card-body">
            <pre><code class="language-php line-numbers"><?php $this->load->view('templates/nodejs_template') ;?></code></pre>
        </div>
    </div>
    <!-- #card-script end -->

    <?php $this->load->view('_snippets/footer'); ?>
</div>
<!-- .container end -->
<?php $this->load->view('_snippets/body_resources'); ?>
</body>
</html>