<?php defined('BASEPATH') OR exit('No direct script access allowed');
?><!DOCTYPE html>
<html lang="en">
<head>
    <?php $this->load->view('_snippets/head_resources'); ?>
</head>
<body>
<!-- .container-fluid start -->
<div class="container-fluid">
    <h1 class="display-3"><i class="fas fa-code fa-fw"></i> Migration Script Generator</h1>
    <ul class="nav nav-tabs">
        <li role="presentation" class="nav-item"><a class="nav-link" href="<?=site_url('generate_migration/init');?>"><i class="fas fa-cog fa-fw"></i> Inital Setup</a></li>
        <li role="presentation" class="nav-item"><a class="nav-link active" href="<?=site_url('generate_migration/generic');?>"><i class="fas fa-sync fa-fw"></i> Generic Script</a></li>
    </ul>
</div>
<!-- .container-fluid end -->

<!-- .container start -->
<div class="container">
    <h1 class="display-4 mb-3">Generate <span class="text-info">Generic</span> Migration Script</h1>

    <!-- #card-form start -->
    <div class="card border-info mb-3">
        <h5 class="card-header bg-info text-white"><i class="fas fa-bolt fa-fw"></i> Generate Script Form</h5>
        <div class="card-body">
            <form method="post" data-parsley-validate>
                <div class="form-group">
                    <label class="control-label">Script Name <span class="text-danger">*</span></label>
                    <input class="form-control" type="text" id="script_name" name="script_name"
                        placeholder="Sample_name" value="<?=set_value('script_name');?>"
                        pattern="<?=REGEX_PARSLEY_FILENAME;?>" required/>
                </div>
                <p class="help-block">Script name criteria:</p>
                <ul class="help-block">
                    <li>No spaces, dashes or special characters E.g. $&amp;# etc.</li>
                    <li>Must begin with a <em>Capital</em> letter.</li>
                    <li>Cannot begin with numbers.</li>
                </ul>
                <p class="help-block">Note: Do not include the version number; it will be generated by system.</p>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        Generate Script <i class="fas fa-check fa-fw"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <!-- #card-form end -->

    <!-- #card-script start -->
    <div class="card border-secondary mb-3">
        <div class="card-header bg-secondary text-white"><i class="fas fa-code fa-fw"></i> Script Preview</div>
        <div class="card-body">
            <pre><code class="language-php line-numbers"><?php $this->load->view('templates/generic_template') ;?></code></pre>
        </div>
    </div>
    <!-- #card-script end -->

    <?php $this->load->view('_snippets/footer'); ?>
</div>
<!-- .container end -->
<?php $this->load->view('_snippets/body_resources'); ?>
</body>
</html>