<?php defined('BASEPATH') OR exit('No direct script access allowed');
?><!DOCTYPE html>
<html lang="en">
<head>
    <?php $this->load->view('_snippets/head_resources'); ?>
</head>
<body>
<!-- .container-fluid start -->
<div class="container-fluid">
    <h1 class="page-header">Migration Script Generator</h1>
    <ul class="nav nav-tabs">
        <li role="presentation"><a href="<?=site_url('generate_migration/init');?>">Inital Setup</a></li>
        <li role="presentation" class="active"><a href="<?=site_url('generate_migration/generic');?>">Generic Script</a></li>
    </ul>
</div>
<!-- .container-fluid end -->

<!-- .container start -->
<div class="container">
    <h2 class="page-header">Generate <span class="text-info">Generic</span> Migration Script</h2>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2 class="panel-title"><i class="fa fa-bolt fa-fw"></i> Generate Script Form</h2>
        </div>
        <div class="panel-body">
            <form method="post" data-parsley-validate>
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label class="control-label">Script Name <span class="text-danger">*</span></label>
                        <input class="form-control" type="text" id="script_name" name="script_name"
                               placeholder="Sample_name" value="<?=set_value('script_name');?>"
                               pattern="<?=REGEX_PARSLEY_FILENAME;?>" required/>
                    </div>
                    <p class="help-block">Script name criteria:</p>
                    <ul class="help-block">
                        <li>No spaces, dashes or special characters E.g. $&amp;# etc.</li>
                        <li>Must begin with a <em>Capital</em> letter.</li>
                        <li>Cannot begin with numbers.</li>
                    </ul>
                    <p class="help-block">Note: Do not include the version number; it will be generated by system.</p>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">
                            Generate Script <i class="fa fa-check fa-fw"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title"><i class="fa fa-code fa-fw"></i> Script Preview</h2>
        </div>
        <div class="panel-body">
            <pre><code class="language-php line-numbers"><?php $this->load->view('templates/generic_template') ;?></code></pre>
        </div>
    </div>

    <?php $this->load->view('_snippets/footer'); ?>
</div>
<!-- .container end -->
<?php $this->load->view('_snippets/body_resources'); ?>
</body>
</html>